dist: focal

language: python

python:
  - "3.9"

cache: pip

before_install:
  - pip install git+https://github.com/evgkanias/sky

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd examples