dist: focal

language: python

python:
  - "3.9"

cache: pip

before_install:
  - cd ~
  - git clone https://github.com/evgkanias/sky
  - cd sky
  - pip install -r requirements.txt
  - pip install .
  - cd ~

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd examples
  - python run_gui.pyw